# Generated by Django 4.1.4 on 2022-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfScrapingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertdatamodel',
            name='observation_values',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
